  language: python
  python:
    - "3.6"
  services:
    - postgresql
  before_script:
    - psql -c 'create database test;' -U postgres
  script:
    -  pytest -x -s -vvv  --disable-pytest-warnings --cov=divorce_life tests/
    - codecov
